### ISSUE TITLE
failed to download your trained pth file, could you share again, thanks

### ISSUE THREAD

**Issue by witding** [OpenDriveLab/LaneSegNet#11]

**Comment by sephyli** [comment]
The model is uploaded to [huggingface.co](http://huggingface.com/). If you cannot access the websit, please consider use a VPN or use a mirror site, e.g. replace [huggingface.co](http://huggingface.com/) in the download link to [hf-mirror.com](http://hf-mirror.com/).

**Comment by witding** [comment]
solved, because https://huggingface.co/OpenDriveLab/lanesegnet_r50_8x1_24e_olv2_subset_A/resolve/main/lanesegnet_r50_8x1_24e_olv2_subset_A.pth    is banned.
