### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by spcrobocar** [OpenDriveLab/LaneSegNet#17]
I followed the instruction to setup a conda env and install all package, but when I ran test.sh, I got a segmentation fault. I did some debug and it seems it is because of the following line `from openlanev2.lanesegment.evaluation.distance import (pairwise)`

Have anyone ever successfully run this repo?

**Comment by sephyli** [comment]
You may can try this alternative environment from [#7](https://github.com/OpenDriveLab/LaneSegNet/issues/7#issuecomment-1909426649).

**Comment by spcrobocar** [comment]
I could not find torchvision 0.15 with cuda 11.7 or 11.8...

**Comment by an-bohr** [comment]
> I was able to install the env as you mentioned. Howevery, in the last step, when I run "pip install -r requirements.txt", I got the following error:
> 
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. nuscenes-devkit 1.1.11 requires Shapely<2.0.0, but you have shapely 2.0.0 which is incompatible.
> 
> nuscenes needs Shapely < 2.0 but openlanev2 needs Shapely > 2.0
> 
> What should I do?

Have you managed to solve the issue since?

**Comment by sephyli** [comment]
That’s a existing denpenency issue in OpenLane-V2. You can install shaply < 2.0.0 manually.
