### ISSUE TITLE
ms_deform_attn_impl_forward implementation for cuda not found

### ISSUE THREAD

**Issue by spcrobocar** [OpenDriveLab/LaneSegNet#18]
I was able to install the env successfully. However, when I run the dist_test.sh, I got the following error:

RuntimeError: ms_deform_attn_impl_forward: implementation for device cuda:1 not found.

I did some search, looks like this is a CUDA issue. However, I was able to run the following python script successfully

import mmcv
import mmcv.ops. 

How can I fix this implementation for device cuda:1 not found issue?

**Comment by sephyli** [comment]
You can try re-install and compile mmcv-full with correct torch version and cuda version. Please follow the mmcv document.
