### ISSUE TITLE
Temporal fusion

### ISSUE THREAD

**Issue by KSonPham** [OpenDriveLab/LaneSegNet#19]
Hi,
It's me again. I've noticed you have some parts of the code containing functions for training with previous frames. Have you run some tests with these and could share some numbers on them?
Best regards,
Pham

**Comment by sephyli** [comment]
Hello, we have debugged it earlier, so it should work properly. However, we haven't conducted any experiments or obtained any results for it yet.

**Comment by KSonPham** [comment]
Thanks for the quick response xD
