### ISSUE TITLE
reproduce error

### ISSUE THREAD

**Issue by chenzyhust** [OpenDriveLab/LaneSegNet#2]
in ped2lane_segment
    assert points.shape[0] == 5
AssertionError

**Comment by sephyli** [comment]
Apologies for the inconvenience caused. We have recently updated the [lane segment](https://github.com/OpenDriveLab/OpenLane-V2/tree/master/data) label. Please download the latest version of the label and then execute the data processing scripts available in this repository.

**Comment by EthanJi29** [comment]
I've met the same problem. Changing to the latest label still doesn't work. Can you tell me the detailed solutions? thx

**Comment by sephyli** [comment]
If you have downloaded the latest label, you may need to run the data processing scripts available in **this repository** that are not the same one in OpenLane-V2. Please refer to the README file.

**Comment by EthanJi29** [comment]
solved. Thanks a lot!

**Comment by xingyun-xy** [comment]
> solved. Thanks a lot!

Hi~, How did you solve it?
