### ISSUE TITLE
兄弟 ，你这个跟maptr有什么区别么 [无意引战，关闭issue了，主要是没太get到与maptr的区别]

### ISSUE THREAD

**Issue by MandyMo** [OpenDriveLab/LaneSegNet#21]
大兄弟，好奇的想问一下，你这个跟maptr有啥区别，没太看出来

**Comment by hli2020** [comment]
你这个作为，Director of the Perception Team, Neolix Autonomous Driving（这啥公司？）

就问出这种问题？

李弘扬

**Comment by hli2020** [comment]
叫 感知团队负责人。这个职位。技术leader. 嗯。
