### ISSUE TITLE
potential bug in loading pipeline

### ISSUE THREAD

**Issue by XR-Lee** [OpenDriveLab/LaneSegNet#22]
there is a unnecessary comma in 
[        self.with_area = with_area,](https://github.com/OpenDriveLab/LaneSegNet/blob/668c2752091966462518ce5076c06693eab8d00a/projects/lanesegnet/datasets/pipelines/loading.py#L68)

which might cause the flag being always True.

**Comment by sephyli** [comment]
Thank you for identifying this issue! I have fixed it.
