### ISSUE TITLE
any tutorial to convert Argoverse V2 data into lane segment annotation?  

### ISSUE THREAD

**Issue by xiaowang12345** [OpenDriveLab/LaneSegNet#25]
Hi,

first, thanks a lot for your great work.  Here I suppose you convert Argoverse V2 HD map data into lane segment annotation automatically.  Could you provide the function？ Thx!

**Comment by sephyli** [comment]
Yes, but we cannot provide that function. We are organizing a competition on OpenLane-V2, and providing it could cause serious label leaking. We hope you can understand and forgive us for that.
