### ISSUE TITLE
Question about evaluation code

### ISSUE THREAD

**Issue by sugar-fly** [OpenDriveLab/LaneSegNet#29]
Hi,

Is there any difference between the evaluation code provided by this repository and the one actually used in the paper? 
Because I found that there is a large gap between the TOP_lsls in the paper and this repository. 

best,

**Comment by sephyli** [comment]
The OpenLane-V2 evaluation kit has been updated to address a loophole in the TOP metric. This update was made after the LaneSegNet submission. Please refer to [#76](https://github.com/OpenDriveLab/OpenLane-V2/issues/76) for more details.

**Comment by sugar-fly** [comment]
Btw, if there are any plans to share the performance of LaneSegNet on the Map Element Bucket?

**Comment by sephyli** [comment]
I just find a similar issue #26. I will have a test and provide the performance in that issue.
