### ISSUE TITLE
The det_t is only 36.09.

### ISSUE THREAD

**Issue by night3759** [OpenDriveLab/LaneSegNet#30]
I trained the model with map_bucket config. The traffic element detection result is only 36.09. I notice that the realization of bbox_head is the same as TopoNet, but the det_t of TopoNet is 48.1. I wondered if I did something wrong? Is there any explanation of this phenomenon?

**Comment by sephyli** [comment]
This is mostly caused by multi-task interference. You can try increasing the loss weight of the TE head.

**Comment by anhtr-nguyn** [comment]
I think the possible reason is the difference between the mm-series version. 

I have train TopoNet on mm-series same as LaneSegNet and there is a significant decrease in the DET_t.
