### ISSUE TITLE
wrong in the corner and how to visualize bev features?

### ISSUE THREAD

**Issue by Miranda0920** [OpenDriveLab/LaneSegNet#31]
Hi,
          Recently I try to train lanesegnet on my own dataset, but I find that the predictions are often wrong when the car turns a corner. Did you meet wrong prediction when the rotation change lots?
          In addition, I wanna draw bev features, but the results seem not correct as below:
      1. calculate the norm the output of BEVFormerEncoder.forward(),(encoder output size is [1,num_query,256], norm result size is [num_query])
      2. then, create image which size is [bev_w,bev_h]
      3. calculate pixel position by ref_2d and pc_range, and set norm of bev feature as color
  Is there any problem? How to draw bev feature correctly?

![企业微信截图_17159292835275(1)](https://github.com/OpenDriveLab/LaneSegNet/assets/19873896/d1c7191a-71e1-4c23-8842-3fa5df598bd6)

**Comment by sephyli** [comment]
Yes, results may degrade when the ego rotates. Consider using BEV rotation augmentation to enhance performance.

For the visualization of BEV feature, you can try using the color map to obtain better visulization quality. Please remember align the coordinate between BEV feature and your image space.
