### ISSUE TITLE
how to detect the curb

### ISSUE THREAD

**Issue by Running-George** [OpenDriveLab/LaneSegNet#33]
Hello, dear author！
Thanks for the nice paper and work. I have a simple question:
In some situation, there will be a curb and a laneline parallel with each other if the lane is the most left or right in a road. how will the model determine the type of the line? give it another class like ( dashed line with curb outside)?

Thanks

**Comment by sephyli** [comment]
In practice, using a separate network to detect curbs could improve accuracy. Additionally, assigning a distinct class to lanelines might be reasonable, depending on your specific use case.
