### ISSUE TITLE
LaneSegNet-tiny and LaneSegNet

### ISSUE THREAD

**Issue by LePetitSirius** [OpenDriveLab/LaneSegNet#34]
What is the difference between LaneSegNet-tiny and LaneSegNet?
Is the config profile lanesegnet_r50_8x1_24e_olv2_subset_A we used version LaneSegNet?
Thank you

**Comment by sephyli** [comment]
Yeah, [this](projects/configs/lanesegnet_r50_8x1_24e_olv2_subset_A.py) is the config of LaneSegNet.
For LaneSegNet-tiny, we only use the last layer features from ResNet. And the image resize are set to 0.33.
