### ISSUE TITLE
Cannot export ONNX model using mmdet v2.26.0

### ISSUE THREAD

**Issue by anhtr-nguyn** [OpenDriveLab/LaneSegNet#35]
Dear authors,

I am following https://mmdetection.readthedocs.io/en/v2.26.0/tutorials/pytorch2onnx.html to export lanesegnet model to ONNX format.

However, the config file is quite different from the format that framework can support. Could you give me some advice ?

**Comment by sephyli** [comment]
Apologies for the delayed response. I haven't had the chance to try the ONNX export and currently don't have the bandwidth to explore it.
