### ISSUE TITLE
Evaluation of TopoNet in the paper

### ISSUE THREAD

**Issue by anhtr-nguyn** [OpenDriveLab/LaneSegNet#36]
Hi

I want to ask about the results of centerline perception in your paper
![image](https://github.com/user-attachments/assets/10e23270-1ed9-4a33-a37e-0cc29ac5985a)

But the result in TopoNet paper is quite different:

![image](https://github.com/user-attachments/assets/6d247158-641c-411e-ae1b-0eaf59f1bc68)

The DET_l is quite lower than the original paper

**Comment by sephyli** [comment]
Hi, the centerline data in TopoNet differs from that in LaneSegNet. We further segment the centerlines by laneline type in this work, resulting in more instances and increasing the problem's complexity.
