### ISSUE TITLE
Why the detection mAP is so low?

### ISSUE THREAD

**Issue by PeiyanGong** [OpenDriveLab/LaneSegNet#38]
Thanks for the awesome paper! This is quite inspiring and innovating.
I am curious why the map element mAP metrics is so different from MapTRv2 paper. For example, in mapTRv2 paper, I see the following:
![maptrv2](https://github.com/user-attachments/assets/b1565f7e-b5d4-4dc1-a130-b498c0a252b0)
However, in LaneSegNet paper, I see this:
![lanesegneteval](https://github.com/user-attachments/assets/51bb7d75-7a40-4e2e-aee0-0ad0e99c7639)
Are these metrics somehow very different? Maybe distance threshold and type of distance? Sorry I feel like I am missing something obvious.

**Comment by PeiyanGong** [comment]
Oh thanks for the reply!
Range diff makes sense.
Could you clarify the "definition of map element" part a little more?
Again huge thanks on the on-time reply!

**Comment by sephyli** [comment]
In the map element detection task, we usually define the ground truth as the merged lane lines, pedestrian crossings, and merged road boundaries. 
For lane segment detection in this paper, the lane lines are unmerged and relatively shorter compared to the original MapTR configuration, leading to a lower mAP.
