### ISSUE TITLE
question about gt centerline? 

### ISSUE THREAD

**Issue by TmacTmac1992** [OpenDriveLab/LaneSegNet#4]
Hi, I noticed the centerline gt was generated by left_lane and right_lane in "LaneSegmentParameterized3D",  what is the difference between original gt centerline and the re-generated centerline?   

centerline = (left_line + right_line) / 2.0

**Comment by sephyli** [comment]
When comparing the original GT centerline to the re-generated one **without interpolation**, they appear to be **identical**.

However, if we interpolate the `left_line` and `right_line` to increase the number of points, there may be a slight difference between the original GT centerline and the re-generated one. Furthermore, it's worth noting that this process is significantly faster than the actual interpolation itself.

**Comment by TmacTmac1992** [comment]
Thanks for your answer!
