### ISSUE TITLE
about visualization 

### ISSUE THREAD

**Issue by winginwind** [OpenDriveLab/LaneSegNet#5]
1. when load config, I got "No module named 'projects'" error
2. I need to do some debug if I want to run **_single_gpu_test_**, but the MMdetection3D visualization API **_show_results_** seems can't support the visualization
3. so I use '--evaluate' finally, but I found the function _**show**_ of  OpenLaneV2_subset_A_LaneSegNet_Dataset isn't impelemented yet

so how can I get the visualization results? Is the code ready to do it? If not, when will you impelement it?

thx

**Comment by sephyli** [comment]
Hi, @winginwind. The visualization [code](https://github.com/OpenDriveLab/LaneSegNet/commit/7cb9c50fe0286cf72414b95b36da4df7b51bfe77) is ready!

You can use `--show` option to visualize the results.
```bash
./dist_test.sh 8 --show
```

**Comment by Ironbrotherstyle** [comment]
> 1. when load config, I got "No module named 'projects'" error
> 2. I need to do some debug if I want to run **_single_gpu_test_**, but the MMdetection3D visualization API **_show_results_** seems can't support the visualization
> 3. so I use '--evaluate' finally, but I found the function _**show**_ of  OpenLaneV2_subset_A_LaneSegNet_Dataset isn't impelemented yet
> 
> so how can I get the visualization results? Is the code ready to do it? If not, when will you impelement it?
> 
> thx

Hi, **_single_gpu_test_** still has error '*** TypeError: show_results() got an unexpected keyword argument 'show'', have you solved the problem?

**Comment by Ironbrotherstyle** [comment]
> Hi, @winginwind. The visualization [code](https://hub.fgit.cf/OpenDriveLab/LaneSegNet/commit/7cb9c50fe0286cf72414b95b36da4df7b51bfe77) is ready!
> 
> You can use `--show` option to visualize the results.
> 
> ```shell
> ./dist_test.sh 8 --show
> ```

Hi, have you tested in **_single_gpu_mode**? It seems that there is a [mmdet3d bug](https://hub.fgit.cf/open-mmlab/mmdetection3d/issues/1119#issue-1081958144) when I tried to run `test.py`.

**Comment by fuchangjie** [comment]
> > Hi, @winginwind. The visualization [code](https://hub.fgit.cf/OpenDriveLab/LaneSegNet/commit/7cb9c50fe0286cf72414b95b36da4df7b51bfe77) is ready!
> > You can use `--show` option to visualize the results.
> > ```shell
> > ./dist_test.sh 8 --show
> > ```
> 
> Hi, have you tested in **_single_gpu_mode**? It seems that there is a [mmdet3d bug](https://hub.fgit.cf/open-mmlab/mmdetection3d/issues/1119#issue-1081958144) when I tried to run `test.py`.

yeah,
first, you can modify the script in test.py like
```
        if not distributed:
            # model = MMDataParallel(model, device_ids=cfg.gpu_ids)
            # outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
            model = MMDataParallel(model, device_ids=[0])
            outputs = single_gpu_test(model, data_loader, False, args.out_dir)
```
then, you can run without distribution like
```
python tools/test.py $CONFIG $CHECKPOINT \
    --out-dir ${WORK_DIR}/test --eval openlane_v2 ${@:2} \
    2>&1 | tee ${WORK_DIR}/test.${timestamp}.log
```

**Comment by Ironbrotherstyle** [comment]
> False, args.out_dir

Thx, similar to my solution, succeed in testing on single GPU, but failed in testing in show mode.

**Comment by lilingnan2** [comment]
Hi, have you found the way to fix the problem in show mode on single GPU? I just met the same problem

**Comment by yokosyun** [comment]
# Solution
- set device_ids = [0]
- disable single_gpu_test show
```
if not distributed:
    # model = MMDataParallel(model, device_ids=cfg.gpu_ids)
    # outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
    model = MMDataParallel(model, device_ids=[0])
    outputs = single_gpu_test(model, data_loader, False, args.out_dir)
```

- only single gpu inference works now
```
./dist_test.sh 1 --show
```

# Explanation
- mmdet3d single_gpu_test show mode is not compatible
- dataset.evaluate will draw result if you set args.show=true

tools/test.py
```
print(dataset.evaluate(outputs, **eval_kwargs))
```

- projects/lanesegnet/datasets/openlanev2_subset_A_lanesegnet_dataset.py
```
def evaluate(self, results, logger=None, show=True, out_dir=None, **kwargs):
```
