### ISSUE TITLE
大型路口+上下文不全时的拓扑连接鲁棒性

### ISSUE THREAD

**Issue by Wastoon** [OpenDriveLab/LaneSegNet#6]
作者你好，真是非常棒的工作啊！
想请教一下，使用预测Lane Segment的状态信息和Ls-Ls彼此之间的逻辑连接关系时，局部上下文的完整性是不是一个非常重要的因素呢？
当遇到一个大型路口，或者是路口处车辆较多且较远处的遮挡比较严重，导致进入车道与退出车道无法在当前时间戳下的环视输入中同时观测完全，那这种情况下，进入LaneSegment和退出LaneSegment之间的逻辑topo连接以及预测的虚拟线是否还鲁棒呢？
想请教多问题有点多，看到主创团队都是国人，就用中文提问啦，期待回复。

**Comment by sephyli** [comment]
您好，在超大路口时，路口远端可能会超出BEV空间的建模距离，在当前的问题定义下，退出车道是不会在GT或Pred中表示完全的。
在一定程度上，BEV检测模型可以模糊地从图像中捕捉到较远处路口的特征，因此路口内的虚拟连接线还是有迹可循的，但预测准确度会受到一定影响。在这种情况下，长距离、大范围的BEV检测还有待探索。
另外，您所提到的遮挡问题，可以通过时序模型或补全模型来在一定程度上得到缓解。

**Comment by Wastoon** [comment]
感谢您的回复！目前在大型路口的长距离、大范围的BEV检测确实是一个还在成长的问题，或许不同焦段的相机传感器能够起到一些作用。还有关于遮挡的问题，使用补全模型真的是一个很有意思的点！会持续关注您后面的工作的，手动点赞👍
