### ISSUE TITLE
OpenLane_v2数据集下载文件缺失

### ISSUE THREAD

**Issue by Dchenhj** [OpenDriveLab/LaneSegNet#8]
非常感谢作者的优秀工作！
我想在您提供的数据集上训练复现论文效果，根据指引，我在 OpenLane-V2 仓内下载了相关数据集，但是训练的时候，提示文件缺失FileNotFoundError: [Errno 2] No such file or directory: 'data/OpenLane-V2/train/00447/image/ring_front_center/315971962049927215.jpg'

检查后发现 data/OpenLane-V2/train/00447/ 文件夹是存在的，但是Image文件夹缺失
同时我注意到 “The Map Element Bucket has been updated as of October 2023. Please ensure you download the most recent data!”

我怀疑是我没有正确下载到最新版本的数据，所以想问一下我应该怎么获取正确的数据？

**Comment by sephyli** [comment]
您需要同时下载OpenLane-V2数据集的Image部分。

**Comment by Dchenhj** [comment]
> 您需要同时下载OpenLane-V2数据集的Image部分。
我已经下载了 
OpenLane-V2_subset_A_image_{0~8}.tar 以及 OpenLane-V2_subset_B_image_{0~8}.tar 的全量图像数据集

**Comment by sephyli** [comment]
在您下载Subset-A的全部0-8的tar压缩包文件并解压在相同文件夹后，每个`data/OpenLane-V2/train/0XXXX`文件夹内应包含image与info两个文件夹。
请您再次查看是否正确下载并解压了全部数据。
