### ISSUE TITLE
训练时长

### ISSUE THREAD

**Issue by raozhongyu** [OpenDriveLab/LaneSegNet#9]
博主您好，我想问下整个训练过程大概要花费多长时间呢？

**Comment by sephyli** [comment]
在8卡V100上大概需要14小时左右，更多细节可以参照[训练日志](https://huggingface.co/OpenDrive/lanesegnet_r50_8x1_24e_olv2_subset_A/resolve/main/20231225_213951.log)。

**Comment by raozhongyu** [comment]
感谢博主！
